### ISSUE TITLE
lesson

### ISSUE THREAD

**Issue by Chicksqace** [zou-hong-run/xinghuo#1]
这个比官网的案例要简单很多，我在想代码能不能直接部署到服务器上。服务器没有node环境，我在想需不需要代理端口，类似数字大屏那种方式，展示在页面上。但是这种方式太耗资源了，你看有没有更好的方案

**Comment by zou-hong-run** [comment]
把这个项目打包压缩，放在服务器的静态目录下面，直接访问该页面应该就可以了

**Comment by Chicksqace** [comment]
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec. 我原本也是这么想的，但报了上面的错误。好像是响应头的问题，我在研究研究

**Comment by zou-hong-run** [comment]
我这里使用的es6 module导入的

**Comment by zou-hong-run** [comment]
你不使用node的话要把module改了，改成script标签去掉module，main.js用到的库全部用script标签引入

**Comment by Chicksqace** [comment]
额，我把服务器上的配置改成了JavaScript，现在可以跑了

**Comment by zou-hong-run** [comment]
ok💪
